### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by DuaneDave** [skyv26/leaderboard#4]
## Hello @skyv26  👋 

After performing the code review exercise on this project, below are the issues raised:

- The base font size was converted to ‘10px’ so, `h1` and `h2` are technically the same. To maintain consistency between the front end and the code base and to not mislead other  developers while reading your code, consider using the default `16px` font size or increase the size of the `h1`  [see here](https://github.com/skyv26/leaderboard/blob/develop/src/public/index.html#:~:text=%3Ch1%20class%3D%22score%2Dheading%22%3ERecent%20Scores%3C/h1%3E)

- For better accessibility,consider improving the contrast ratio for the presentational texts so users with eye defects can have equal experience with those that don’t.

- To follow HTML best practices, consider using an `a` tag for the logo instead of a `p` tag [see here](https://github.com/skyv26/leaderboard/blob/develop/src/public/index.html#:~:text=%3Cp%20class%3D%22header%2Dlogo%22%3ELeaderboard%3C/p%3E) 

Happy Coding 😄

**Comment by skyv26** [comment]
Thanks @DuaneDave. I have made the changes as per your request.
